### ISSUE TITLE
Import service and endpoints from swagger file

### ISSUE THREAD

**Issue by schovi** [adidas-group/mashery-toolbelt#16]
- from given swagger file generate service -> endpoint structure with default values
- option switch which changes how multiple HTTP methods for one path are handled
  1. Creates one endpoint with multiple HTTP methods
  2. Creates multiple endpoints for each HTTP method

TODOS:

- [x] Convert `[ ]` into `( )`
- [x] Add argument to set http or https

**Comment by schovi** [comment]
@rathonit1 Hi, released version `mashery-toolbelt@2.0.1` (skipping that alpha, it is pointless :) )
There is detail how to use it https://github.com/adidas-group/mashery-toolbelt/blob/master/README.md#swagger-import

**Comment by rathonit1** [comment]
@schovi   
Got error, can you please help

$ mashery-toolbelt swagger-import test-swagger-import.yaml \
>                                 --organisation=8201****056d --multiMethodEndpoint \
>                                 --name='DEV (Play) swagger import' --trafficDomain='company.mashery.com' \
>                                 --publicDomain='company.mashery.com' \
>                                 --endpointDomain='internal.company.biz'

  error: unknown option `--name'

**Comment by schovi** [comment]
@rathonit1 `mashery-toolbelt@2.0.2` published faster than thought and forgot to mention in immediately :S I think you can just `npm i -g mashery-toolbelt` next time which should install latest version always.

**Comment by rathonit1** [comment]
Hello @schovi ,

Now getting new error as mentioned follows. Will share you the swagger file separately.

Creating failed:
ReferenceError: createApi is not defined
    at action (C:\Users\nitesh.rathore01\AppData\Roaming\npm\node_modules\mashery-toolbelt\src\workflow\swagger\import.js:21:11)
    at inquirer.prompt.then (C:\Users\nitesh.rathore01\AppData\Roaming\npm\node_modules\mashery-toolbelt\src\utils\confirmChanges.js:18:14)
    at <anonymous>

Since it is not able to create configs in Mashery, we are not able to verify much. 
few comments as follows:

1.	Naming Convention for Endpoints
a.	In the command line we gave name value (as 'DEV (Test) Play Swagger Import) which ideally should be for used for “Service_Name”, and for “endpoints_names” we should append few more details from swagger file as follows:
i.	API Root EDP, so finally Endpoint name will become as  -- 'DEV (Test) Play Swagger Import API Root EDP’
ii.	List of Orders -- 'DEV (Test) Play Swagger Import List of Orders EDP’

2.	TransportProtocol
a.	Please use by default, http for both inbound and outbound
b.	In case we need to use https, we should be able to provide as Command input (for outboundTransportProtocol & InboundTransportProtocol separately).

**Comment by rathonit1** [comment]
@schovi 
I am getting two type of errors/issues:

#1 --> with limited user access lets say a user has access to only a particular organization we got error as follows:

Creating failed:
{ RequestError: [POST] https://api.mashery.com/v3/rest/services failed:403 ({"errorCode":403,"errorMessage":"Forbidden"})
    at payloadPromise.then.payload (C:\Users\nitesh.rathore01\AppData\Roaming\npm\node_modules\mashery-toolbelt\src\lib\client\request.js:105:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'request_error', name: 'RequestError' }

#2 --> when user has Area access got following error
Creating failed:
{ RequestError: [POST] https://api.mashery.com/v3/rest/services failed:400 ({"errorCode":400,"errors":[{"property":"name","message":"Property 'name' does not match the required pattern, /^[\\w\\-\\. ():]*$/."}],"errorMessage":"Unable to create service definition."})
    at payloadPromise.then.payload (C:\Users\nitesh.rathore01\AppData\Roaming\npm\node_modules\mashery-toolbelt\src\lib\client\request.js:105:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'request_error', name: 'RequestError' }

**Comment by schovi** [comment]
@rathonit1 

1. This is definitely something I can't affect. At the beginning, I had the similar problem and you tried to contact Mashery support about it.

2. How does the JSON look like? Especially service and endpoint names. As you can see there are allowed characters: `a-z 0-9 - . ( ) :`

**Comment by rathonit1** [comment]
@schovi  looks like it is affected with [] square bracket.
need to change it to () round one.

**Comment by rathonit1** [comment]
@schovi 
FYI Organization name is not mapped correctly, this needs some fix :)

**Comment by schovi** [comment]
@rathonit1 What do you mean by "organisation name"?
